[package]
name = "cargo-magisk"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
clap = { version = "4.5.50", features = ["derive"] }
rstest = "0.26.1"
serde = "1.0.228"
toml = "0.9.8"
